### ISSUE TITLE
ReadCIFAR10ToNDArray.sc is missing

### ISSUE THREAD

**Issue by izhangzhihao** [ThoughtWorksInc/DeepLearning.scala-website#10]
https://raw.githubusercontent.com/ThoughtWorksInc/DeepLearning.scala-website/master/demo/ReadCIFAR10ToNDArray.sc
is 404: Not Found

**Comment by Atry** [comment]
It should be https://raw.githubusercontent.com/ThoughtWorksInc/DeepLearning.scala-website/v1.0.0-doc/ipynbs/ReadCIFAR10ToNDArray.sc
