### ISSUE TITLE
Jupyter notebook documentation: invalid javadoc links

### ISSUE THREAD

**Issue by mlucchini** [ThoughtWorksInc/DeepLearning.scala-website#8]
In GettingStarted.ipynb and possibly other Jupyter notebooks, links to Javadoc don't lead anywhere and/or lead to classes that don't seem to exist anymore.

Example of such a link:
https://static.javadoc.io/com.thoughtworks.deeplearning/plugins-builtins_2.11/2.0.0/com/thoughtworks/deeplearning/plugins/RawINDArrayLayers$ImplicitsApi$INDArrayLayerOps.html

should probably be something like:

https://javadoc.io/doc/com.thoughtworks.deeplearning/deeplearning_2.11/2.0.0 [...]

**Comment by Atry** [comment]
Thank you for your report.
It should be fixed now.

The page http://deeplearning.thoughtworks.school/demo/GettingStarted.html should be updated once Travis CI complete.
